/*
 * Copyright (c) 2026, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * For full license text, see the LICENSE file in the repo root or https://www.apache.org/licenses/LICENSE-2.0
 */

import * as fs from 'fs';
import * as path from 'path';

// Type definitions for sidebar items based on Docusaurus structure
type SidebarItemConfig =
  | string
  | {
      type: 'category' | 'doc' | 'link' | 'html' | 'autogenerated';
      label?: string;
      items?: SidebarItemConfig[];
      link?: {
        type: string;
        id: string;
      };
      value?: string;
      dirName?: string;
      id?: string;
    };

interface PackageMetadata {
  name: string;
  displayName: string;
  description: string;
  emoji: string;
  hasTypedocDocs: boolean;
  typedocIndex?: number;
}

/**
 * Reads package.json or pyproject.toml to extract metadata
 */
function getPackageMetadata(packagePath: string): PackageMetadata | null {
  const packageJsonPath = path.join(packagePath, 'package.json');
  const pyprojectPath = path.join(packagePath, 'pyproject.toml');

  try {
    if (fs.existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
      return {
        name: packageJson.name,
        displayName: packageJson.name,
        description: packageJson.description || '',
        emoji: '📦',
        hasTypedocDocs: false,
      };
    } else if (fs.existsSync(pyprojectPath)) {
      const pyproject = fs.readFileSync(pyprojectPath, 'utf-8');
      const nameMatch = pyproject.match(/name\s*=\s*"([^"]+)"/);
      const descMatch = pyproject.match(/description\s*=\s*"([^"]+)"/);
      return {
        name: nameMatch ? nameMatch[1] : path.basename(packagePath),
        displayName: nameMatch ? nameMatch[1] : path.basename(packagePath),
        description: descMatch ? descMatch[1] : '',
        emoji: '🐍',
        hasTypedocDocs: false,
      };
    }
  } catch (error) {
    console.warn(`Failed to read package metadata for ${packagePath}:`, error);
  }

  return null;
}

/**
 * Maps package names to their emoji and display names
 */
const PACKAGE_CONFIG: Record<string, { emoji: string; displayName: string }> = {
  '@agentscript/parser-tree-sitter': {
    emoji: '🌳',
    displayName: 'Parser',
  },
  '@agentscript/monaco': {
    emoji: '📝',
    displayName: 'Monaco',
  },
  '@agentscript/test-scripts': {
    emoji: '🧪',
    displayName: 'Test Scripts',
  },
};

/**
 * Scans a directory for packages and returns metadata
 */
function scanPackages(baseDir: string): PackageMetadata[] {
  const packages: PackageMetadata[] = [];

  if (!fs.existsSync(baseDir)) {
    return packages;
  }

  const entries = fs.readdirSync(baseDir, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const packagePath = path.join(baseDir, entry.name);
      const metadata = getPackageMetadata(packagePath);

      if (metadata) {
        // Apply custom configuration if available
        const config = PACKAGE_CONFIG[metadata.name];
        if (config) {
          metadata.emoji = config.emoji;
          metadata.displayName = config.displayName;
        }

        packages.push(metadata);
      }
    }
  }

  return packages;
}

/**
 * Maps TypeDoc sidebar items to package names
 */
function mapTypedocSidebarToPackages(
  typedocSidebar: SidebarItemConfig[]
): Map<string, number> {
  const packageMap = new Map<string, number>();

  typedocSidebar.forEach((item, index) => {
    if (typeof item === 'object' && 'label' in item && item.label) {
      packageMap.set(item.label, index);
    }
  });

  return packageMap;
}

/**
 * Generates sidebar items for packages
 */
function generatePackageSidebarItems(
  packages: PackageMetadata[],
  typedocSidebar: SidebarItemConfig[]
): SidebarItemConfig[] {
  const typedocMap = mapTypedocSidebarToPackages(typedocSidebar);
  const items: SidebarItemConfig[] = [];

  for (const pkg of packages) {
    const typedocIndex = typedocMap.get(pkg.name);
    const hasTypedocDocs = typedocIndex !== undefined;
    const typedocItem = hasTypedocDocs ? typedocSidebar[typedocIndex] : null;

    const item: SidebarItemConfig = {
      type: 'category',
      label: `${pkg.emoji} ${pkg.displayName}`,
      items:
        hasTypedocDocs &&
        typedocItem &&
        typeof typedocItem === 'object' &&
        'items' in typedocItem
          ? typedocItem.items || []
          : [{ type: 'html', value: '<i>Documentation coming soon</i>' }],
    };

    if (hasTypedocDocs && typeof item === 'object') {
      item.link = {
        type: 'doc',
        id: `api/${pkg.name}/index`,
      };
    }

    items.push(item);
  }

  return items;
}

/**
 * Main function to generate the complete sidebar configuration
 * @param workspaceRoot - The root directory of the workspace
 * @param typedocSidebar - The TypeDoc-generated sidebar items (pass empty array if not available)
 */
export function generateSidebar(
  workspaceRoot: string,
  typedocSidebar: SidebarItemConfig[] = []
): SidebarItemConfig[] {
  // Scan for dialects and packages
  const dialectsPath = path.join(workspaceRoot, 'dialects');
  const packagesPath = path.join(workspaceRoot, 'packages');

  const dialects = scanPackages(dialectsPath);
  const packages = scanPackages(packagesPath);

  // Generate sidebar items
  const dialectItems = generatePackageSidebarItems(dialects, typedocSidebar);
  const packageItems = generatePackageSidebarItems(packages, typedocSidebar);

  // Build the complete sidebar
  return [
    'intro',
    {
      type: 'category',
      label: '🚀 Getting Started',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: '🏗️ Architecture',
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    ...dialectItems,
    ...packageItems,
    {
      type: 'category',
      label: '🤝 Contributing',
      items: [{ type: 'autogenerated', dirName: 'contributing' }],
    },
  ];
}
