/*
 * Copyright (c) 2026, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * For full license text, see the LICENSE file in the repo root or https://www.apache.org/licenses/LICENSE-2.0
 */

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Language Guide',
      items: [
        'language/syntax',
        'language/blocks',
        'language/reasoning',
        'language/expressions',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: 'Packages',
      items: [
        'packages/overview',
        'packages/language',
        'packages/dialect',
        'packages/tooling',
        'packages/cli',
        'packages/vscode-extension',
      ],
    },
    {
      type: 'category',
      label: 'Extending',
      items: [
        'extending/custom-lint-passes',
        'extending/custom-dialects',
        'extending/language-service',
      ],
    },
    {
      type: 'category',
      label: 'Custom Dialects',
      link: { type: 'doc', id: 'dialects/index' },
      items: [
        'dialects/index',
        {
          type: 'category',
          label: 'Agentforce',
          link: { type: 'doc', id: 'dialects/agentforce/agent-script' },
          items: [
            'dialects/agentforce/agent-script',
            'dialects/agentforce/ascript-lang',
            'dialects/agentforce/ascript-blocks',
            'dialects/agentforce/ascript-flow',
            'dialects/agentforce/ascript-manage',
            {
              type: 'category',
              label: 'Examples',
              items: [
                'dialects/agentforce/examples/ascript-examples',
                'dialects/agentforce/examples/ascript-example-customer-support',
                'dialects/agentforce/examples/ascript-example-rag-jargon',
                'dialects/agentforce/examples/ascript-examples-multi-turn',
              ],
            },
            {
              type: 'category',
              label: 'Patterns',
              items: [
                'dialects/agentforce/patterns/ascript-patterns',
                'dialects/agentforce/patterns/ascript-patterns-action-chaining',
                'dialects/agentforce/patterns/ascript-patterns-topic-selector',
                'dialects/agentforce/patterns/ascript-patterns-conditionals',
                'dialects/agentforce/patterns/ascript-patterns-fetch-data',
                'dialects/agentforce/patterns/ascript-patterns-filtering',
                'dialects/agentforce/patterns/ascript-patterns-required-flow',
                'dialects/agentforce/patterns/ascript-patterns-multi-turn',
                'dialects/agentforce/patterns/ascript-patterns-resource-references',
                'dialects/agentforce/patterns/ascript-patterns-system-overrides',
                'dialects/agentforce/patterns/ascript-patterns-transitions',
                'dialects/agentforce/patterns/ascript-patterns-variables',
              ],
            },
            {
              type: 'category',
              label: 'Reference',
              items: [
                'dialects/agentforce/reference/ascript-reference',
                'dialects/agentforce/reference/ascript-ref-actions',
                'dialects/agentforce/reference/ascript-ref-before-after-reasoning',
                'dialects/agentforce/reference/ascript-ref-expressions',
                'dialects/agentforce/reference/ascript-ref-instructions',
                'dialects/agentforce/reference/ascript-ref-operators',
                'dialects/agentforce/reference/ascript-ref-tools',
                'dialects/agentforce/reference/ascript-ref-utils',
                'dialects/agentforce/reference/ascript-ref-variables',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Agent Fabric',
          link: { type: 'doc', id: 'dialects/agentfabric/index' },
          items: ['dialects/agentfabric/index'],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [{ type: 'autogenerated', dirName: 'contributing' }],
    },
  ],
};

export default sidebars;
