/*
 * Copyright (c) 2026, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * For full license text, see the LICENSE file in the repo root or https://www.apache.org/licenses/LICENSE-2.0
 */

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Language Guide',
      items: [
        'language/syntax',
        'language/blocks',
        'language/reasoning',
        'language/expressions',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: 'Packages',
      items: [
        'packages/overview',
        'packages/language',
        'packages/dialect',
        'packages/tooling',
        'packages/cli',
        'packages/vscode-extension',
      ],
    },
    {
      type: 'category',
      label: 'Extending',
      items: [
        'extending/custom-lint-passes',
        'extending/custom-dialects',
        'extending/language-service',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [{ type: 'autogenerated', dirName: 'contributing' }],
    },
  ],
};

export default sidebars;
