# Copyright (c) 2026, Salesforce, Inc.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# For full license text, see the LICENSE file in the repo root or https://www.apache.org/licenses/LICENSE-2.0

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    stop_grace_period: 30s
    init: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - EMSDK_QUIET=1
      - PYTHONUNBUFFERED=1
      - NODE_ENV=development
