/*
 * Portions of this file are adapted from shadcn/ui (https://ui.shadcn.com)
 * MIT License — Copyright (c) 2023 shadcn
 * See https://github.com/shadcn-ui/ui/blob/main/LICENSE.md
 *
 * Modifications copyright (c) 2026 Salesforce, Inc.
 * SPDX-License-Identifier: MIT
 */

// This file is generated by icon spritesheet generator

export const iconNames = [
  'update',
  'trash',
  'sun',
  'reset',
  'question-mark-circled',
  'plus',
  'pencil-2',
  'pencil-1',
  'passkey',
  'moon',
  'magnifying-glass',
  'lock-open-1',
  'lock-closed',
  'link-2',
  'laptop',
  'github-logo',
  'file-text',
  'exit',
  'envelope-closed',
  'download',
  'dots-horizontal',
  'cross-1',
  'clock',
  'check',
  'camera',
  'avatar',
  'arrow-right',
  'arrow-left',
] as const;

export type IconName = (typeof iconNames)[number];
